import Navbar from "@/app/Navbar";
import bgStars from "@/public/gif/background-stars.gif";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { type ReactNode } from "react";

import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundImage: `url(${bgStars.src})`,
          backgroundRepeat: "repeat",
        }}
      >
        <Providers>
          <div>
            <Navbar />
            {props.children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
